### ISSUE TITLE
Configuration options for Debounce

### ISSUE THREAD

**Issue by V4G4X** [TabbyML/vim-tabby#13]
I was hoping this would be an option in `~/.tabby-client/agent/config.toml`.  

But [this](https://tabby.tabbyml.com/docs/extensions/configurations/) didn't mention anything.   
So maybe it is IDE-specific.  

If that's the case, please add the configuration option for the nvim plugin.

As you can tell, I'd prefer fewer auto-completion prompts when I type, and this seems like a standard enough configuration.

**Comment by icycodes** [comment]
Hi, @V4G4X

You can try adding the following configuration in your `~/.tabby-client/agent/config.toml` file:

```toml
[completion.debounce]
mode = "fixed"
interval = 1000 # ms
```

Some unstable or infrequently used configurations are not included in the standard config template and documentation for the sake of brevity and readability. For more information, please refer to the Tabby source code at:
https://github.com/TabbyML/tabby/blob/main/clients/tabby-agent/src/AgentConfig.ts
https://github.com/TabbyML/tabby/blob/main/clients/tabby-agent/src/configFile.ts

**Comment by V4G4X** [comment]
Yeah I think I'm getting fewer prompts with this.  
Thanks a lot @icycodes!
