### ISSUE TITLE
Allow connection to https url with self-signed certificate

### ISSUE THREAD

**Issue by dtrckd** [TabbyML/vim-tabby#18]
I set tabby in a server, behind a nginx reverse proxy, with a self-signed certificate for https.

But the agent seems to be unable to connect in this case (I verified that it supports the http connection and it does).

Is it possible to support an “insecure” connection (curl -k)?

**Comment by icycodes** [comment]
Hello, @dtrckd, 
To address this issue, you can add your self-signed certificate to your operating system's CA registry. The tabby-agent now supports loading system-wide CA certificates starting from version 1.4.
