### ISSUE TITLE
recipe to integrate with vim-cmp ?

### ISSUE THREAD

**Issue by pjz** [TabbyML/vim-tabby#4]
Anyone have a recipe to integrate with vim-cmp?  Right now they both use Tab which conflicts: I see the tabby completion, but then the vim-cmp completions also show, and end up preferred for selection.  vim-cmp, though, is extensible, so it should be possible to add tabby as a completion provider.

**Comment by icycodes** [comment]
Hi, @pjz 
Thank you for bringing up this issue.  
The vim-tabby plugin is designed to be independent of other completion plugins. But it should be possible to fork the plugin source code and modify them to be compatible with vim-cmp.

Additionally, I would recommend reaching out to our [Slack community](https://join.slack.com/t/tabbycommunity/shared_invite/zt-1xeiddizp-bciR2RtFTaJ37RBxr8VxpA), or open an issue in our [main repo](https://github.com/TabbyML/tabby/issues/new). As this repo is for releasing vim-tabby and may have lower traffic.

**Comment by pjz** [comment]
Okay, I made https://github.com/TabbyML/tabby/issues/1024 instead of this one.
